baseURL = "https://schuttejoe.github.io/"
languageCode = "en-us"
title = "Rendering Equations"
theme = "medial"

[Params]
    description = "Joe Schutte"
    author = "Joe Schutte"
    copyright = " "
    highlight = true
    highlightStyle = "monokai-sublime"
    font = "Cambria"
    homeImage = "img/SanMiguel.png"
	homeImageLink = "/post/"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Blog"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

[[menu.icon]]
    url = "mailto:schutte.joe@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/schuttejoe/"
    name = "twitter"
    weight = 2

[[menu.icon]]
    url = "https://github.com/schuttejoe/"
    name = "github"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/joe-schutte-32540212/"
    name = "linkedin"
    weight = 4